# Generated by Django 3.0.2 on 2021-07-03 11:08

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='category_thumnail')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('about_category', models.TextField(max_length=20000)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='course_name', unique=True)),
                ('file', models.FileField(upload_to='course_media/')),
                ('description', models.TextField()),
                ('course_thumbnail', models.ImageField(upload_to='course_thumbnail')),
                ('external_links', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_books', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField()),
                ('choose', models.CharField(choices=[('meets community guidelines', 'Meets Community Guidelines'), ('withdraw course', 'Withdraw Course')], default=1, max_length=255)),
                ('total_course_time', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_a_career_path', multiselectfield.db.fields.MultiSelectField(choices=[('Software Development', 'Software Development'), ('UI/UX/Graphic Design', 'UI/UX/Graphic Design'), ('Robotics', 'Robotics'), ('Microsoft Offices', 'Microsoft Offices'), ('Cyber Security', 'Cyber Security'), ('Networking', 'Networking'), ('AI/Data Science/Machine Learning', 'AI/Data Science/Machine Learning')], max_length=3000)),
                ('have_you_had_any_previous_IT_knowledge', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('Not so Much', 'Not so Much')], max_length=255)),
                ('Github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
